[platformio]
default_envs = d1_mini
test_dir = test/logger

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_speed = 115200
build_src_filter = +<*> -<wifi_check.cpp> -<sensor_check.cpp>
lib_deps =
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15
    bblanchon/ArduinoJson@7.4.2

[env:wifi_check]
extends = env:d1_mini
build_src_filter = -<*> +<wifi_check.cpp>
lib_deps =

[env:sensor_check]
extends = env:d1_mini
build_src_filter = -<*> +<sensor_check.cpp>
lib_deps =
    adafruit/DHT sensor library@1.4.7
    adafruit/Adafruit Unified Sensor@1.1.15

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_src_filter = -<*> +<logger_protocol.cpp> +<sampling_window.cpp>
lib_deps =
    bblanchon/ArduinoJson@7.4.2
